kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  proxy-protocol: "True"
  real-ip-header: "proxy-protocol"
  set-real-ip-from: "0.0.0.0/0"
  client-max-body-size: "10m"

